# Generated by Django 4.1.7 on 2023-06-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
